### ISSUE TITLE
Unexpected auto_open behavior

### ISSUE THREAD

**Issue by lowderchris** [d-lamb/fluxon-mhd#16]
When executing some of the built-in examples described in the wiki tutorials, the auto_open flag does not always seem to allow fluxons to split and break open beyond the specified boundary. For the examples contained within fluxon-mhd/pdl/menagerie, some follow this breaking open behavior as expected (_several-open-lines_, _twisted-emerging-1_, _twisted-emerging-2_, etc). The example _twisted_ does not follow this behavior, and allows fluxons to expand without bounds.

Note - on a hunch, I re-ran the _twisted_ example code, and all appeared to work correctly. I'll look into this a bit further.

**Comment by lowderchris** [comment]
It looks as though this might have been a problem with text encoding while copying and pasting sample code. Sorry, auto_open, I didn't mean to suggest you were buggy.

**Comment by drzowie** [comment]
:-D
